### PR TITLE
Started first order analysis section

### PR DESCRIPTION
**Pull request by Joseph-Burley**
First few paragraphs and equations of the first order analysis section.
Both main.tex and Lab1Part1.tex are compatible with each other and will
compile. Some commands in main.tex were commented out because those
packages are missing on this (windows) machine.

### CODE REVIEW

**Comment by theNerd247** [comment]
What's with the mass*length thingy?

**Comment by Joseph-Burley** [comment]
Part of the prelab was to use dimensional analysis to show that the time
constant RC is in units of time.

**Comment by theNerd247** [comment]
Ok. Makes sense. can you rewrite that section as to not use words? I suggest we use `T, L, M, I` for time, length, mass, and current units respectively.

**Comment by Joseph-Burley** [comment]
I went ahead and made those changes to my copy.

**Pull request closed without merging**
